name: Generate Blog Post HTML

on:
  repository_dispatch:
    types: [sanity-post-published]

jobs:
  generate-post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install fs path
        
      - name: Generate post HTML
        run: node sanity-post-generator.js
        
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add posts/*.html
          git commit -m "Add blog post HTML files" || echo "No changes to commit"
          git push 